// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6HcNYfwKvjM1qLddVjJUPKK-0Tv22J4',
    appId: '1:966946958668:web:6625c2fdb52f0412cf33e9',
    messagingSenderId: '966946958668',
    projectId: 'fir-2db2d',
    authDomain: 'fir-2db2d.firebaseapp.com',
    storageBucket: 'fir-2db2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMuY6RKJlb_NpSFP5e77jbfGNLM7qd30',
    appId: '1:966946958668:android:fe51b93390cad082cf33e9',
    messagingSenderId: '966946958668',
    projectId: 'fir-2db2d',
    storageBucket: 'fir-2db2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdJVDmtmhu4TqUgWaS-OtL15N9QjxXd8',
    appId: '1:966946958668:ios:e4d4cf9e90951bbccf33e9',
    messagingSenderId: '966946958668',
    projectId: 'fir-2db2d',
    storageBucket: 'fir-2db2d.firebasestorage.app',
    androidClientId: '966946958668-kblfegdj9j4bpn7lboru6fus3lgnlkgr.apps.googleusercontent.com',
    iosClientId: '966946958668-b8pbm1715187l9mujugpj5ee5kv64fqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

}